CREATE NONCLUSTERED INDEX [ndxSourceItemID] ON [dbo].[Links]
(
	[SourceDatabase] ASC,
	[SourceItemID] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
	DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
	ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, FILLFACTOR = 80) 
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ndxTargetItemID] ON [dbo].[Links]
(
	[TargetDatabase] ASC,
	[TargetItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
	DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
	ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, FILLFACTOR = 80) 
ON [PRIMARY]
GO
